name: Deploy Terraform

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: 662863386798
  AWS_REGION: eu-central-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: ["demo123", "environments/demo"]

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-radio-user-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=${{ matrix.folder }} init

      - name: Terraform Plan
        run: terraform -chdir=${{ matrix.folder }} plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=${{ matrix.folder }} apply -auto-approve